= Music Service
:toc:

== Summary

== Development Quickstart Guide

=== Local Development Environment

==== Technology Stack
====
- Java 17
- Maven 3.8
- Spring boot 2.6.6
====

==== Start the app
This app has a spring boot back-end.

* Start the back-end
====
  mvn clean install
  java -Denvironment=localhost  -jar target/music-service-0.1-SNAPSHOT.jar
====


==== Tests

The tests are written in Junit5. 
There is one unit test to test integration to Music Brainz API using MockWebServer.

MusicServiceApiITTest.java:
This is an Integration test that performs the required operation using Wiremock to mock external API.

== Runtime Environment and Deployment
curl --location --request GET 'http://localhost:8086/musify/music-artist/details/f27ec8db-af05-4f36-916e-3d57f91ecf5e'

== Test Data
* MBID: f27ec8db-af05-4f36-916e-3d57f91ecf5e 
* MBID: 
* MBID: 

== Notes:
* Only Music Brainz API is implemented in real time. Data for Other 3 APIs is hard-coded in application memory to avoid implementing same boilerplate logic.
* 