spring:
  application:
    name: music-service

  profiles:
      active: ${environment:localhost}

  output:
    ansi:
      enabled: always
  main:
    allow-bean-definition-overriding: true

  jmx:
    enabled: false

server:
  port: 8086

service:
  music-brainz:
    api:
      url: http://musicbrainz.org/ws/2