package com.musicservice.client;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.musicservice.client.model.WikipediaResponse;
import java.util.HashMap;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

@Slf4j
@Component
public class WikipediaClient {

  private final HashMap<String, JsonNode> WIKIPEDIA_MAP;
  private final ObjectMapper objectMapper = new ObjectMapper();

  public WikipediaClient() throws JsonProcessingException {
    WIKIPEDIA_MAP = new HashMap<>();
    WIKIPEDIA_MAP.put("https://en.wikipedia.org/wiki/Michael_Jackson", objectMapper.readTree("{\"type\":\"standard\",\"title\":\"Michael Jackson\",\"displaytitle\":\"<span class=\\\"mw-page-title-main\\\">Michael Jackson</span>\",\"namespace\":{\"id\":0,\"text\":\"\"},\"wikibase_item\":\"Q2831\",\"titles\":{\"canonical\":\"Michael_Jackson\",\"normalized\":\"Michael Jackson\",\"display\":\"<span class=\\\"mw-page-title-main\\\">Michael Jackson</span>\"},\"pageid\":14995351,\"thumbnail\":{\"source\":\"https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Michael_Jackson_in_1988.jpg/191px-Michael_Jackson_in_1988.jpg\",\"width\":191,\"height\":320},\"originalimage\":{\"source\":\"https://upload.wikimedia.org/wikipedia/commons/3/31/Michael_Jackson_in_1988.jpg\",\"width\":300,\"height\":502},\"lang\":\"en\",\"dir\":\"ltr\",\"revision\":\"1114378591\",\"tid\":\"4f94b5b0-458b-11ed-bca8-a1d4f9adb6bf\",\"timestamp\":\"2022-10-06T06:00:33Z\",\"description\":\"American singer, songwriter, and dancer (1958–2009)\",\"description_source\":\"local\",\"content_urls\":{\"desktop\":{\"page\":\"https://en.wikipedia.org/wiki/Michael_Jackson\",\"revisions\":\"https://en.wikipedia.org/wiki/Michael_Jackson?action=history\",\"edit\":\"https://en.wikipedia.org/wiki/Michael_Jackson?action=edit\",\"talk\":\"https://en.wikipedia.org/wiki/Talk:Michael_Jackson\"},\"mobile\":{\"page\":\"https://en.m.wikipedia.org/wiki/Michael_Jackson\",\"revisions\":\"https://en.m.wikipedia.org/wiki/Special:History/Michael_Jackson\",\"edit\":\"https://en.m.wikipedia.org/wiki/Michael_Jackson?action=edit\",\"talk\":\"https://en.m.wikipedia.org/wiki/Talk:Michael_Jackson\"}},\"extract\":\"Michael Joseph Jackson was an American singer, songwriter, dancer, and philanthropist. Dubbed the \\\"King of Pop\\\", he is regarded as one of the most significant cultural figures of the 20th century. Over a four-decade career, his contributions to music, dance, and fashion, along with his publicized personal life, made him a global figure in popular culture. Jackson influenced artists across many music genres; through stage and video performances, he popularized complicated dance moves such as the moonwalk, to which he gave the name, as well as the robot. He is the most awarded individual music artist in history.\",\"extract_html\":\"<p><b>Michael Joseph Jackson</b> was an American singer, songwriter, dancer, and philanthropist. Dubbed the \\\"King of Pop\\\", he is regarded as one of the most significant cultural figures of the 20th century. Over a four-decade career, his contributions to music, dance, and fashion, along with his publicized personal life, made him a global figure in popular culture. Jackson influenced artists across many music genres; through stage and video performances, he popularized complicated dance moves such as the moonwalk, to which he gave the name, as well as the robot. He is the most awarded individual music artist in history.</p>\"}"));
    WIKIPEDIA_MAP.put("https://en.wikipedia.org/wiki/Cold_Cave", objectMapper.readTree("{\"type\":\"standard\",\"title\":\"Cold Cave\",\"displaytitle\":\"<span class=\\\"mw-page-title-main\\\">Cold Cave</span>\",\"namespace\":{\"id\":0,\"text\":\"\"},\"wikibase_item\":\"Q4036392\",\"titles\":{\"canonical\":\"Cold_Cave\",\"normalized\":\"Cold Cave\",\"display\":\"<span class=\\\"mw-page-title-main\\\">Cold Cave</span>\"},\"pageid\":24120595,\"thumbnail\":{\"source\":\"https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Cold_Cave_Thalia_Hall_2018.jpg/320px-Cold_Cave_Thalia_Hall_2018.jpg\",\"width\":320,\"height\":248},\"originalimage\":{\"source\":\"https://upload.wikimedia.org/wikipedia/commons/5/52/Cold_Cave_Thalia_Hall_2018.jpg\",\"width\":3903,\"height\":3024},\"lang\":\"en\",\"dir\":\"ltr\",\"revision\":\"1096663768\",\"tid\":\"1ca797d0-37e4-11ed-a1ce-7fd908bc255c\",\"timestamp\":\"2022-07-05T22:26:59Z\",\"description\":\"American gothic rock band\",\"description_source\":\"local\",\"content_urls\":{\"desktop\":{\"page\":\"https://en.wikipedia.org/wiki/Cold_Cave\",\"revisions\":\"https://en.wikipedia.org/wiki/Cold_Cave?action=history\",\"edit\":\"https://en.wikipedia.org/wiki/Cold_Cave?action=edit\",\"talk\":\"https://en.wikipedia.org/wiki/Talk:Cold_Cave\"},\"mobile\":{\"page\":\"https://en.m.wikipedia.org/wiki/Cold_Cave\",\"revisions\":\"https://en.m.wikipedia.org/wiki/Special:History/Cold_Cave\",\"edit\":\"https://en.m.wikipedia.org/wiki/Cold_Cave?action=edit\",\"talk\":\"https://en.m.wikipedia.org/wiki/Talk:Cold_Cave\"}},\"extract\":\"Cold Cave is the moniker for the music of Wesley Eisold, described as a \\\"collage of darkwave, noise, and synthpop.\\\" A number of reviewers note the affinity with early 1980s post-punk and early synthpop, in particular Joy Division and New Order.\",\"extract_html\":\"<p><b>Cold Cave</b> is the moniker for the music of Wesley Eisold, described as a \\\"collage of darkwave, noise, and synthpop.\\\" A number of reviewers note the affinity with early 1980s post-punk and early synthpop, in particular Joy Division and New Order.</p>\"}"));
    WIKIPEDIA_MAP.put("https://en.wikipedia.org/wiki/Nirvana_(band)", objectMapper.readTree("{\"type\":\"standard\",\"title\":\"Nirvana (band)\",\"displaytitle\":\"<span class=\\\"mw-page-title-main\\\">Nirvana (band)</span>\",\"namespace\":{\"id\":0,\"text\":\"\"},\"wikibase_item\":\"Q11649\",\"titles\":{\"canonical\":\"Nirvana_(band)\",\"normalized\":\"Nirvana (band)\",\"display\":\"<span class=\\\"mw-page-title-main\\\">Nirvana (band)</span>\"},\"pageid\":21231,\"thumbnail\":{\"source\":\"https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Nirvana_around_1992.jpg/320px-Nirvana_around_1992.jpg\",\"width\":320,\"height\":302},\"originalimage\":{\"source\":\"https://upload.wikimedia.org/wikipedia/commons/1/19/Nirvana_around_1992.jpg\",\"width\":367,\"height\":346},\"lang\":\"en\",\"dir\":\"ltr\",\"revision\":\"1115295982\",\"tid\":\"ff46a250-48d0-11ed-b8b2-e3ad0d1adad6\",\"timestamp\":\"2022-10-10T19:23:15Z\",\"description\":\"American rock band\",\"description_source\":\"local\",\"content_urls\":{\"desktop\":{\"page\":\"https://en.wikipedia.org/wiki/Nirvana_(band)\",\"revisions\":\"https://en.wikipedia.org/wiki/Nirvana_(band)?action=history\",\"edit\":\"https://en.wikipedia.org/wiki/Nirvana_(band)?action=edit\",\"talk\":\"https://en.wikipedia.org/wiki/Talk:Nirvana_(band)\"},\"mobile\":{\"page\":\"https://en.m.wikipedia.org/wiki/Nirvana_(band)\",\"revisions\":\"https://en.m.wikipedia.org/wiki/Special:History/Nirvana_(band)\",\"edit\":\"https://en.m.wikipedia.org/wiki/Nirvana_(band)?action=edit\",\"talk\":\"https://en.m.wikipedia.org/wiki/Talk:Nirvana_(band)\"}},\"extract\":\"Nirvana was an American rock band formed in Aberdeen, Washington, in 1987. Founded by lead singer and guitarist Kurt Cobain and bassist Krist Novoselic, the band went through a succession of drummers, most notably Chad Channing, before recruiting Dave Grohl in 1990. Nirvana's success popularized alternative rock, and they were often referenced as the figurehead band of Generation X. Their music maintains a popular following and continues to influence modern rock culture.\",\"extract_html\":\"<p><b>Nirvana</b> was an American rock band formed in Aberdeen, Washington, in 1987. Founded by lead singer and guitarist Kurt Cobain and bassist Krist Novoselic, the band went through a succession of drummers, most notably Chad Channing, before recruiting Dave Grohl in 1990. Nirvana's success popularized alternative rock, and they were often referenced as the figurehead band of Generation X. Their music maintains a popular following and continues to influence modern rock culture.</p>\"}"));
  }

  public WikipediaResponse getWikipediaByTitle(String titleLink) throws JsonProcessingException {
    return objectMapper.treeToValue(WIKIPEDIA_MAP.get(titleLink), WikipediaResponse.class);
  }
}
